// src/config/constants.js

const USER_ROLES = {
    ADMIN: 'ADMIN',
    INSTRUCTOR: 'INSTRUCTOR',
    STUDENT: 'STUDENT',
    GUEST: 'GUEST',
}

const USER_STATUS = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    BANNED: 'BANNED',
}

const COURSE_LEVEL = {
    BEGINNER: 'BEGINNER',
    INTERMEDIATE: 'INTERMEDIATE',
    ADVANCED: 'ADVANCED',
}

const COURSE_STATUS = {
    DRAFT: 'DRAFT',
    PUBLISHED: 'PUBLISHED',
    ARCHIVED: 'ARCHIVED',
}

const ENROLLMENT_STATUS = {
    ACTIVE: 'ACTIVE',
    COMPLETED: 'COMPLETED',
    DROPPED: 'DROPPED',
}

const TRANSCRIPT_STATUS = {
    IDLE: 'idle',
    PROCESSING: 'processing',
    COMPLETED: 'completed',
    FAILED: 'failed',
    CANCELLED: 'cancelled',
}

const HLS_STATUS = {
    IDLE: 'idle',
    PROCESSING: 'processing',
    COMPLETED: 'completed',
    FAILED: 'failed',
}

const PAYMENT_STATUS = {
    PENDING: 'PENDING',
    PAID: 'PAID',
    FAILED: 'FAILED',
    REFUNDED: 'REFUNDED',
    PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
    REFUND_PENDING: 'REFUND_PENDING',
    REFUND_FAILED: 'REFUND_FAILED',
}

const PENDING_TIME = {
    PENDING_TIMEOUT_MS: 15 * 60 * 1000, // 15 phút
}

const TRANSACTION_STATUS = {
    PENDING: 'PENDING',
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED',
    REFUNDED: 'REFUNDED',
}

const PAYMENT_GATEWAY = {
    VNPAY: 'VNPay',
    MOMO: 'MoMo',
}

const REFUND_REASON_TYPES = {
    MEDICAL: 'MEDICAL',
    FINANCIAL_EMERGENCY: 'FINANCIAL_EMERGENCY',
    DISSATISFACTION: 'DISSATISFACTION',
    OTHER: 'OTHER',
}

const REFUND_TYPES = {
    FULL: 'FULL',
    PARTIAL: 'PARTIAL',
}

const COUPON_TYPES = {
    PERCENT: 'PERCENT',
    FIXED: 'FIXED',
    NEW_USER: 'NEW_USER',
}

const REFUND_POLICY = {
    FULL_REFUND_MAX_PROGRESS: 20, // %
    FULL_REFUND_MAX_DAYS: 7, // days from paidAt
    PARTIAL_REFUND_MIN_PROGRESS: 20, // %
    PARTIAL_REFUND_MAX_PROGRESS: 50, // %
    PARTIAL_REFUND_PROCESSING_FEE: 0.2, // 20% processing fee
    OFFER_EXPIRY_HOURS: 48, // hours for student to accept/reject offer
}

const NOTIFICATION_TYPES = {
    // Student notifications
    ENROLLMENT_SUCCESS: 'ENROLLMENT_SUCCESS',
    LESSON_COMPLETED: 'LESSON_COMPLETED',
    COURSE_COMPLETED: 'COURSE_COMPLETED',
    QUIZ_GRADED: 'QUIZ_GRADED',
    PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    ORDER_CANCELLED: 'ORDER_CANCELLED',

    // Admin notifications
    USER_REGISTERED: 'USER_REGISTERED',
    USER_STATUS_CHANGED: 'USER_STATUS_CHANGED',
    USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
    COURSE_PENDING_APPROVAL: 'COURSE_PENDING_APPROVAL',
    COURSE_APPROVED: 'COURSE_APPROVED',
    COURSE_REJECTED: 'COURSE_REJECTED',
    COURSE_PUBLISHED: 'COURSE_PUBLISHED',
    LARGE_ORDER: 'LARGE_ORDER',
    REFUND_REQUEST: 'REFUND_REQUEST',
    SYSTEM_ALERT: 'SYSTEM_ALERT',
    DAILY_REPORT: 'DAILY_REPORT',

    // Instructor notifications
    NEW_ENROLLMENT: 'NEW_ENROLLMENT',
    COURSE_APPROVAL_STATUS: 'COURSE_APPROVAL_STATUS',
    NEW_REVIEW: 'NEW_REVIEW',
    STUDENT_COMPLETED_COURSE: 'STUDENT_COMPLETED_COURSE',
    NEW_QUESTION: 'NEW_QUESTION',
    QUIZ_SUBMISSION: 'QUIZ_SUBMISSION',
    PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
    REVENUE_REPORT: 'REVENUE_REPORT',
    PAYOUT_PROCESSED: 'PAYOUT_PROCESSED',
    TRANSCRIPT_COMPLETED: 'TRANSCRIPT_COMPLETED',
    VIDEO_UPLOADED: 'VIDEO_UPLOADED',
}

const AI_INTERACTION_TYPES = {
    QUICK_QA: 'QUICK_QA',
    LESSON_HELP: 'LESSON_HELP',
    COURSE_RECOMMENDATION: 'COURSE_RECOMMENDATION',
    COURSE_OVERVIEW: 'COURSE_OVERVIEW',
    CONCEPT_EXPLANATION: 'CONCEPT_EXPLANATION',
    CODE_REVIEW: 'CODE_REVIEW',
    GENERAL_CHAT: 'GENERAL_CHAT',
}

const ALLOWED_IMAGE_TYPES = [
    'image/jpeg',
    'image/png',
    'image/jpg',
    'image/webp',
]
const ALLOWED_VIDEO_TYPES = ['video/mp4', 'video/mp3', 'video/webm']
const ALLOWED_DOCUMENT_TYPES = [
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
]

const MAX_FILE_SIZE = 10 * 1024 * 1024 // 10MB
const MAX_IMAGE_SIZE = 5 * 1024 * 1024 // 5MB
const MAX_VIDEO_SIZE = 500 * 1024 * 1024 // 500MB

const UPLOAD_TYPES = {
    IMAGE: {
        AVATAR: 'avatar',
        THUMBNAIL: 'thumbnail',
        SYSTEM: 'system',
        GENERAL: 'general',
    },
    VIDEO: {
        LESSON: 'lesson',
        PREVIEW: 'preview',
        GENERAL: 'general',
    },
    DOCUMENT: {
        TRANSCRIPT: 'transcript',
        MATERIAL: 'material',
        GENERAL: 'general',
    },
}

const UPLOAD_STATUS = {
    PENDING: 'pending',
    PROCESSING: 'processing',
    COMPLETED: 'completed',
    FAILED: 'failed',
}

const ERROR_CODES = {
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
    AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    PAYMENT_ERROR: 'PAYMENT_ERROR',
    FILE_UPLOAD_ERROR: 'FILE_UPLOAD_ERROR',
    RATE_LIMIT_ERROR: 'RATE_LIMIT_ERROR',
}

const HTTP_STATUS = {
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    TOO_MANY_REQUESTS: 429,
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
}

const PAGINATION = {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 20,
    MAX_LIMIT: 100,
}

const JWT_EXPIRY = {
    ACCESS_TOKEN: '7d',
    REFRESH_TOKEN: '30d',
    EMAIL_VERIFICATION: '24h',
    PASSWORD_RESET: '1h',
}

const RATE_LIMITS = {
    PUBLIC: {
        windowMs: 15 * 60 * 1000, // 15 minutes
        max: 100,
    },
    AUTH: {
        windowMs: 15 * 60 * 1000,
        max: 5,
    },
    API: {
        windowMs: 15 * 60 * 1000,
        max: 300,
    },
    AI: {
        windowMs: 60 * 1000, // 1 minute
        max: 20,
    },
    UPLOAD: {
        windowMs: 60 * 1000,
        max: 10,
    },
}

export {
    USER_ROLES,
    USER_STATUS,
    COURSE_LEVEL,
    COURSE_STATUS,
    ENROLLMENT_STATUS,
    TRANSCRIPT_STATUS,
    HLS_STATUS,
    PAYMENT_STATUS,
    TRANSACTION_STATUS,
    PAYMENT_GATEWAY,
    REFUND_REASON_TYPES,
    REFUND_TYPES,
    REFUND_POLICY,
    NOTIFICATION_TYPES,
    AI_INTERACTION_TYPES,
    ALLOWED_IMAGE_TYPES,
    ALLOWED_VIDEO_TYPES,
    ALLOWED_DOCUMENT_TYPES,
    MAX_FILE_SIZE,
    MAX_IMAGE_SIZE,
    MAX_VIDEO_SIZE,
    ERROR_CODES,
    HTTP_STATUS,
    PAGINATION,
    JWT_EXPIRY,
    RATE_LIMITS,
    PENDING_TIME,
    UPLOAD_TYPES,
    UPLOAD_STATUS,
    COUPON_TYPES,
}
